version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: chitchat-mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: chitchat_db
      MYSQL_ROOT_PASSWORD: 1234 # Buraya güçlü bir şifre yazın
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: